# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Kjorelista' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kjøreliste
  
  # Redux-like global state handling
  pod 'ReSwift', '~>4.0.0'
  
  # Firebase integration
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

end
